-- The Alignment Times' own "Compatibility Index" -- a satirical, original
-- composite score per country pair, NOT a redistribution of Hofstede/World
-- Values Survey/GLOBE (all three are research/non-commercial-use only,
-- confirmed before building this). Generated by
-- scripts/generate-compatibility-scores.mts, which grounds each pair's
-- score in the site's own already-published Global Office / Out of Office
-- articles for that pair (via Sanity's `countries[]` article field) plus a
-- few cited open hard-data stats -- editorial synthesis, not a scientific
-- instrument, matching the site's Economist-meets-Onion voice.
--
-- One row per unordered country pair (country_a_slug < country_b_slug
-- alphabetically, enforced by the generator, not by a DB constraint --
-- keep it simple).

create table if not exists public.country_compatibility (
  id                  uuid default gen_random_uuid() primary key,

  country_a_slug      text not null,
  country_a_name      text not null,
  country_b_slug      text not null,
  country_b_name      text not null,

  overall_score       int not null check (overall_score between 0 and 100),
  verdict             text not null,

  -- Array of { label, score (0-100), blurb } -- see generate-compatibility-scores.mts
  -- for the fixed dimension set (Work-Life Balance, Hierarchy & Formality,
  -- Communication Style, Punctuality Culture, Social Bonding).
  dimensions          jsonb not null default '[]'::jsonb,

  -- Array of { slug, section, title } -- the published articles this score
  -- was grounded in, so the public page can link back to them.
  source_articles     jsonb not null default '[]'::jsonb,

  generated_at        timestamptz not null default now(),

  unique (country_a_slug, country_b_slug)
);

alter table public.country_compatibility enable row level security;

create policy "Public read"
  on public.country_compatibility
  for select
  using (true);

create policy "Service role write"
  on public.country_compatibility
  for all
  using (false);

create index if not exists country_compatibility_a_idx on public.country_compatibility(country_a_slug);
create index if not exists country_compatibility_b_idx on public.country_compatibility(country_b_slug);
